### ISSUE TITLE
shows items on reload/zone change

### ISSUE THREAD

**Issue by darkseid4nk** [syndenbock/Farmer#11]
Every time I change zones or reload every crafting item I have shows up on my screen. Would be nice if it only showed up on looting.

**Comment by syndenbock** [comment]
Does this happen in Classic/Wotlk or Retail?

**Comment by syndenbock** [comment]
In testing I found that reagent bank information is no longer available right after login, causing the addon to think the reagent bank is empty. Knowing Blizzards awful item events it will take a bit to find a fix.

**Comment by syndenbock** [comment]
This should be fixed in version 3.14.2. Feel free to reopen the issue if not.
