### ISSUE TITLE
Error newest update 12/2/2022

### ISSUE THREAD

**Issue by Wraiven** [syndenbock/Farmer#12]
5x Farmer error: ...dOns/Farmer/detectors/Reputation/RegularFactions.lua:129: attempt to compare two nil values
[string "@Farmer/classes/CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Farmer/classes/CallbackHandler.lua"]:48: in function `call'
[string "@Farmer/core/EventFunnel.lua"]:12: in function <Farmer/core/EventFunnel.lua:10>

**Comment by syndenbock** [comment]
That was a stupid oversight from me but should be fixed in version 3.15.1 I just uploaded.
