### ISSUE TITLE
LUA error upon login

### ISSUE THREAD

**Issue by Wraiven** [syndenbock/Farmer#13]
2x Farmer error: ...dOns/Farmer/detectors/Reputation/RegularFactions.lua:66: Usage: local isMajorFaction = C_Reputation.IsMajorFaction(factionID)
[string "@Farmer/core/Events.lua"]:29: in function <Farmer/core/Events.lua:25>
[string "=[C]"]: in function `pcall'
[string "@Farmer/utils/Utils.lua"]:123: in function <Farmer/utils/Utils.lua:122>
[string "@Farmer/classes/CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Farmer/classes/CallbackHandler.lua"]:48: in function `call'
[string "@Farmer/core/Events.lua"]:10: in function <Farmer/core/Events.lua:9>

**Comment by syndenbock** [comment]
This issue is caused by another addon interfering with Farmer by collapsing headers in the reputation pane while Farmer is reading the reputations. In the developer branch this is already being detectted including an informational message.
