### ISSUE TITLE
Radar Node Issues

### ISSUE THREAD

**Issue by Cknnuggets** [syndenbock/Farmer#17]
Since the release of phase two,  the nodes whilst using radar appear to move in a fixed direction of travel instead of dynamically turning with the character

**Comment by syndenbock** [comment]
Unfortunately there is nothing I can do about this issue. 
In the latest Wrath patch Blizzard seem to have broken something major in their event system so some events are no longer being fired reliably. One of those events is <<CVAR_UPDATE>> which signalizes that a setting has changed.
When you enable the radar, Farmer updates the "Rotate minimap" setting but the game no longer tells other addons that setting has been changed, causing them to misplace the icons.
The only thing you could do about this is enabling the "Rotate minimap" setting outside of the farm radar and reload so other addons read the setting anew and already place the icons as they would need to with the radar enabled.
