### ISSUE TITLE
Lua error when item levels hidden

### ISSUE THREAD

**Issue by Anonomit** [syndenbock/Farmer#18]
In the Items plugin, [getItemLevelText()](https://github.com/syndenbock/Farmer/blob/f67ef86b9ff966a4b9fd761184f9d32d2d2d91bf/Farmer/plugins/Items/Items.lua#L143) returns nil when `options.showEquipmentItemLevels ~= true`.

This causes an error when the result is later concatenated with a string, such as [here on line 298](https://github.com/syndenbock/Farmer/blob/f67ef86b9ff966a4b9fd761184f9d32d2d2d91bf/Farmer/plugins/Items/Items.lua#L298).

**Comment by syndenbock** [comment]
Thanks for reporting this, I'll clean up that code a bit as it's pretty inconsistent across that plugin and will fix that issue in there.
The fix should be out some time tomorrow.

**Comment by syndenbock** [comment]
This was fixed in version 3.22.
