### ISSUE TITLE
Looting items

### ISSUE THREAD

**Issue by Peregran** [syndenbock/Farmer#20]
12x ...dOns/Farmer/detectors/Reputation/RegularFactions.lua:59: attempt to index local 'factionInfo' (a nil value)
[string "@Farmer/detectors/Reputation/RegularFactions.lua"]:165: in function <...dOns/Farmer/detectors/Reputation/RegularFactions.lua:164>
[string "=[C]"]: ?
[string "@Farmer/Core.lua"]:36: in function <Farmer/Core.lua:35>
[string "@Farmer/classes/CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Farmer/classes/CallbackHandler.lua"]:58: in function `call'
[string "@Farmer/core/EventFunnel.lua"]:12: in function <Farmer/core/EventFunnel.lua:10>

Locals:

**Comment by syndenbock** [comment]
Something seems to have changed in Blizzards API that sometimes causes nil to be returned for faction information. I just released a new version that handles those cases.
