### ISSUE TITLE
SoD after patch, when looting something

### ISSUE THREAD

**Issue by dh-harald** [syndenbock/Farmer#21]
Hi,

When I'm looting something, I can't see messages on the screen and the following error drops:

```
Message: ...AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua:374: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
Time: Sun Sep 29 10:32:04 2024
Count: 7
Stack: ...AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua:374: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "@Interface/AddOns/Farmer/Core.lua"]:36: in function <Interface/AddOns/Farmer/Core.lua:35>
[string "@Interface/AddOns/Farmer/classes/CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Interface/AddOns/Farmer/classes/CallbackHandler.lua"]:58: in function `call'
[string "@Interface/AddOns/Farmer/core/Events.lua"]:11: in function <Interface/AddOns/Farmer/core/Events.lua:10>

Locals: 
```

I'm using the latest version of addon, SoD, english client

**Comment by illutian** [comment]
Same, here's my version:

292x Farmer/widgets/MessageFrames/MessageFrame.lua:374: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "@Farmer/widgets/MessageFrames/MessageFrame.lua"]:374: in function <Farmer/widgets/MessageFrames/MessageFrame.lua:373>
[string "@Farmer/widgets/MessageFrames/MessageFrame.lua"]:418: in function <Farmer/widgets/MessageFrames/MessageFrame.lua:410>
[string "@Farmer/widgets/MessageFrames/MessageFrame.lua"]:454: in function <Farmer/widgets/MessageFrames/MessageFrame.lua:452>
[string "=(tail call)"]: ?
[string "@Farmer/widgets/MessageFrames/MessageFrame.lua"]:573: in function <Farmer/widgets/MessageFrames/MessageFrame.lua:572>
[string "=(tail call)"]: ?
[string "@Farmer/widgets/MessageFrames/DataMessageFrame.lua"]:97: in function <...ns/Farmer/widgets/MessageFrames/DataMessageFrame.lua:89>
[string "=(tail call)"]: ?
[string "@Farmer/widgets/MessageFrames/DataMessageModeFrame.lua"]:92: in function `AddIconMessageWithData'
[string "@Farmer/widgets/MessageFrames/DataMessageModeFrame.lua"]:129: in function `AddIconMessageWithData'
[string "@Farmer/main/Print.lua"]:56: in function <Farmer/main/Print.lua:55>
[string "@Farmer/plugins/Reputation/Reputation.lua"]:81: in function <...faceFarmer/plugins/Reputation/Reputation.lua:55>
...
[string "@Farmer/Core.lua"]:36: in function <Farmer/Core.lua:35>
[string "@Farmer/classes/CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Farmer/classes/CallbackHandler.lua"]:58: in function `call'
[string "@Farmer/core/Yell.lua"]:14: in function `yell'
[string "@Farmer/detectors/Reputation/RegularFactions.lua"]:119: in function <...dOns/Farmer/detectors/Reputation/RegularFactions.lua:118>
[string "@Farmer/detectors/Reputation/RegularFactions.lua"]:151: in function <...dOns/Farmer/detectors/Reputation/RegularFactions.lua:139>
[string "@Farmer/detectors/Reputation/RegularFactions.lua"]:161: in function `callback'
[string "@Farmer/detectors/Reputation/RegularFactions.lua"]:89: in function <...dOns/Farmer/detectors/Reputation/RegularFactions.lua:64>
[string "@Farmer/detectors/Reputation/RegularFactions.lua"]:166: in function <...dOns/Farmer/detectors/Reputation/RegularFactions.lua:165>
[string "@Farmer/core/Events.lua"]:40: in function <Farmer/core/Events.lua:38>

Locals:
self = <table> {
 fading = true
 shadowOffset = <table> {
 }
 ALIGNMENT_LEFT = "LEFT"
 visibleTime = 3
 fontFlags = "OUTLINE"
 resetCallbacks = <table> {
 }
 spacing = 0
 mode = <table> {
 }
 subspaceCount = 6
 fadeDuration = 1
 INSERTMODE_APPEND = "APPEND"
 insertMode = "PREPEND"
 GROW_DIRECTION_DOWN = "DOWN"
 anchor = Frame {
 }
 shadowColors = <table> {
 }
 messageInfo = <table> {
 }
 GROW_DIRECTION_UP = "UP"
 subspaces = <table> {
 }
 iconSize = 18
 framePool = <table> {
 }
 iconScale = 1
 font = "Fonts\FRIZQT__.TTF"
 fontSize = 18
 INSERTMODE_PREPEND = "PREPEND"
 ALIGNMENT_RIGHT = "RIGHT"
 ALIGNMENT_CENTER = "CENTER"
}
fontString = FontString {
}
alignment = nil

**Comment by syndenbock** [comment]
This is a followup error due to an error Blizzard introduced in WoW Classic where the template for sliders is not loaded: https://github.com/Stanzilla/WoWUIBugs/issues/645

Due to this, the addon cannot create the options panel and therefore uses the default settings of the addon. In those default settings one value wasn't set, causing this error. Even with the value set the addon will always use default settings which is bad, so I'll have to find a workaround for the Blizzard bug (or they fix it themselves hopefully).

**Comment by dh-harald** [comment]
Looks, the bug has been fixed. I can see my loots again
