### ISSUE TITLE
Gatherer icons dissapear

### ISSUE THREAD

**Issue by Nohony** [syndenbock/Farmer#4]
Hi,
I'm currently using Tracking Switcher addon for automatic aura switching (herb / mining). When im using Farm Radar and whenever aura switch, some gatherer icons may randomly dissapear and randomply appear again. Only happens when moving. Yellow dots, which indicates veins or herbs, appear normally.
Nohony
Edit: Tracking Switcher isnt the problem, switching auras manually do the same error.

**Comment by syndenbock** [comment]
This is the same issue as described in issue #6, looking for a fix already.
