### ISSUE TITLE
Route missing from Farm Hud overlay 3.13

### ISSUE THREAD

**Issue by MajorKryme** [syndenbock/Farmer#7]
I reverted back to previous build and it's working find...I'll just wait.  Not much more info to give...I updated to latest version and existing route lines disappeared, not from the minimap, but from the farm hud overlay.  I reverted back to ver 3.12.5, made zero adjustments or updates to any existing addon and all my routes are showing again both on the minimap and the farm hud.

I'm using it for WotlK classic.  So long as it continues to work for me, I'll stick with 3.12.5.  Just wanted to provide some info to you.

**Comment by syndenbock** [comment]
Has this not been fixed in version 3.13.1 already?
