### ISSUE TITLE
Unable to clickthrough Radar

### ISSUE THREAD

**Issue by TooFad3d** [syndenbock/Farmer#8]
Hi, I'm unable to click through the radar to mine/herb.

Your addon seems to be the only Farming HUD addon that works with Zygor Guides, but in order to actually mine or herb, I have to toggle off the Radar or zoom in all the way so the node/herb is on the far left/right of the screen.

![ex1](https://user-images.githubusercontent.com/117228000/199342380-4e6cba60-c053-417c-a35b-c9ff442697fe.png)
![ex2](https://user-images.githubusercontent.com/117228000/199342383-ab02f8f0-7680-433b-a811-341aef5ff327.png)

**Comment by syndenbock** [comment]
Even though the mouse cursor does not change its appearance, you should be able to right-click nodes through the farm radar.
If not, could you try disabling the "enable tooltips for default nodes" in the farm radar section and see if it works then? (You'll have to toggle the radar off and on once to apply the setting).

**Comment by TooFad3d** [comment]
> 
Haha, i'm a dumbass. Didn't even bother to try right clicking. That indeed does work even though the mouse doesnt show it.

Thank you for the fast reply!
