### ISSUE TITLE
Equipped Reagent Bag shown as new Item

### ISSUE THREAD

**Issue by Hayato2846** [syndenbock/Farmer#9]
Hey!

Since I equipped my reagent bag it's always shown as a new looted Item after a Loading Screen.  Would it be possible to filter this out? 

Thanks :)

**Comment by syndenbock** [comment]
Are you playing on Classic/WotLK or Retail?

**Comment by Hayato2846** [comment]
Retail

**Comment by dh-harald** [comment]
I've same issue on Classic, but it shows my keys as new items sometimes... (Farmer version: 3.14.2)
screenshot: https://ibb.co/q1Y8Xnj
I've opened a cooking bag with 3 northern spices

**Comment by syndenbock** [comment]
I added support for the reagent bag and the keyring now, I need to test it a bit first though.
If you wanna test it yourself you can download the latest version of the development branch [here](https://github.com/syndenbock/Farmer/archive/refs/heads/develop.zip) and copy the "Farmer" subfolder into your addons folder.
